#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# chkconfig: 123 69 68
# description: Confluent Schema Registry

. /etc/init.d/functions

if [ -f /etc/sysconfig/kafka-connect-distributed-server ]; then
    . /etc/sysconfig/kafka-connect-distributed-server
fi

start() {
    echo -n "Starting Kafka"
    daemon --user $KAFKA_USER /usr/bin/kafka-connect-distributed-server-start -daemon $KAFKA_CONFIG
}

stop() {
    echo -n "Stopping Kafka"
    /usr/bin/kafka-connect-distributed-server-stop
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
    ;;
esac